ALTER TABLE `tickets` ADD `motivo_categoria` text DEFAULT 'sin_clasificar' NOT NULL;
--> statement-breakpoint
-- Backfill determinista sobre una columna nueva. `motivo` y `resumen` se leen,
-- pero nunca se reescriben. Primero manda el motivo; el resumen solo se usa si
-- el motivo no coincide con ninguna categoría conocida.
UPDATE `tickets`
SET `motivo_categoria` = CASE
  WHEN lower(coalesce(`motivo`, '')) LIKE '%liquidaci%'
    OR lower(coalesce(`motivo`, '')) LIKE '%baja laboral%'
    OR lower(coalesce(`motivo`, '')) LIKE '%desvincul%'
    OR lower(coalesce(`motivo`, '')) LIKE '%despido%'
    OR lower(coalesce(`motivo`, '')) LIKE '%renuncia%'
    OR lower(coalesce(`motivo`, '')) LIKE '%periodo de prueba%'
    OR lower(coalesce(`motivo`, '')) LIKE '%período de prueba%'
    OR lower(coalesce(`motivo`, '')) LIKE '%uniforme%'
    THEN 'bajas_liquidacion'
  WHEN lower(coalesce(`motivo`, '')) LIKE '%recibo de sueldo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%recibo sueldo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%recibo de haberes%'
    OR lower(coalesce(`motivo`, '')) LIKE '%duplicado%recibo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%certificado laboral%'
    OR lower(coalesce(`motivo`, '')) LIKE '%constancia laboral%'
    OR lower(coalesce(`motivo`, '')) LIKE '%constancia de trabajo%'
    THEN 'recibos_documentacion'
  WHEN lower(coalesce(`motivo`, '')) LIKE '%vacaci%'
    OR lower(coalesce(`motivo`, '')) LIKE '%licencia%'
    OR lower(coalesce(`motivo`, '')) LIKE '%dias de descanso%'
    OR lower(coalesce(`motivo`, '')) LIKE '%días de descanso%'
    THEN 'vacaciones_licencias'
  WHEN lower(coalesce(`motivo`, '')) LIKE '%sueldo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%haber%'
    OR lower(coalesce(`motivo`, '')) LIKE '%pago no recibido%'
    OR lower(coalesce(`motivo`, '')) LIKE '%no me pag%'
    OR lower(coalesce(`motivo`, '')) LIKE '%no cobro%'
    OR lower(coalesce(`motivo`, '')) LIKE '%deposit%'
    OR lower(coalesce(`motivo`, '')) LIKE '%acredit%'
    OR lower(coalesce(`motivo`, '')) LIKE '%aguinaldo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%anticipo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%diferencia salarial%'
    THEN 'haberes_pagos'
  WHEN lower(coalesce(`motivo`, '')) LIKE '%postul%'
    OR lower(coalesce(`motivo`, '')) LIKE '%empleo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%trabajo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%curriculum%'
    OR lower(coalesce(`motivo`, '')) LIKE '%vacante%'
    OR lower(coalesce(`motivo`, '')) LIKE '%incorpor%'
    THEN 'empleo_postulaciones'
  WHEN lower(coalesce(`motivo`, '')) LIKE '%llamada perdida%'
    OR lower(coalesce(`motivo`, '')) LIKE '%devolv%llamada%'
    OR lower(coalesce(`motivo`, '')) LIKE '%quien%llamo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%quién%llamó%'
    OR lower(coalesce(`motivo`, '')) LIKE '%comunicar%'
    OR lower(coalesce(`motivo`, '')) LIKE '%contactar%'
    THEN 'contacto_general'
  WHEN lower(coalesce(`motivo`, '')) LIKE '%reclamo%'
    OR lower(coalesce(`motivo`, '')) LIKE '%reclamar%'
    OR lower(coalesce(`motivo`, '')) LIKE '%queja%'
    OR lower(coalesce(`motivo`, '')) LIKE '%disconform%'
    THEN 'reclamos'
  WHEN lower(coalesce(`resumen`, '')) LIKE '%liquidaci%'
    OR lower(coalesce(`resumen`, '')) LIKE '%baja laboral%'
    OR lower(coalesce(`resumen`, '')) LIKE '%desvincul%'
    OR lower(coalesce(`resumen`, '')) LIKE '%despido%'
    OR lower(coalesce(`resumen`, '')) LIKE '%renuncia%'
    OR lower(coalesce(`resumen`, '')) LIKE '%periodo de prueba%'
    OR lower(coalesce(`resumen`, '')) LIKE '%período de prueba%'
    OR lower(coalesce(`resumen`, '')) LIKE '%uniforme%'
    THEN 'bajas_liquidacion'
  WHEN lower(coalesce(`resumen`, '')) LIKE '%recibo de sueldo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%recibo sueldo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%recibo de haberes%'
    OR lower(coalesce(`resumen`, '')) LIKE '%duplicado%recibo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%certificado laboral%'
    OR lower(coalesce(`resumen`, '')) LIKE '%constancia laboral%'
    OR lower(coalesce(`resumen`, '')) LIKE '%constancia de trabajo%'
    THEN 'recibos_documentacion'
  WHEN lower(coalesce(`resumen`, '')) LIKE '%vacaci%'
    OR lower(coalesce(`resumen`, '')) LIKE '%licencia%'
    OR lower(coalesce(`resumen`, '')) LIKE '%dias de descanso%'
    OR lower(coalesce(`resumen`, '')) LIKE '%días de descanso%'
    THEN 'vacaciones_licencias'
  WHEN lower(coalesce(`resumen`, '')) LIKE '%sueldo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%haber%'
    OR lower(coalesce(`resumen`, '')) LIKE '%pago no recibido%'
    OR lower(coalesce(`resumen`, '')) LIKE '%no me pag%'
    OR lower(coalesce(`resumen`, '')) LIKE '%no cobro%'
    OR lower(coalesce(`resumen`, '')) LIKE '%deposit%'
    OR lower(coalesce(`resumen`, '')) LIKE '%acredit%'
    OR lower(coalesce(`resumen`, '')) LIKE '%aguinaldo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%anticipo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%diferencia salarial%'
    THEN 'haberes_pagos'
  WHEN lower(coalesce(`resumen`, '')) LIKE '%postul%'
    OR lower(coalesce(`resumen`, '')) LIKE '%empleo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%trabajo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%curriculum%'
    OR lower(coalesce(`resumen`, '')) LIKE '%vacante%'
    OR lower(coalesce(`resumen`, '')) LIKE '%incorpor%'
    THEN 'empleo_postulaciones'
  WHEN lower(coalesce(`resumen`, '')) LIKE '%llamada perdida%'
    OR lower(coalesce(`resumen`, '')) LIKE '%devolv%llamada%'
    OR lower(coalesce(`resumen`, '')) LIKE '%quien%llamo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%quién%llamó%'
    OR lower(coalesce(`resumen`, '')) LIKE '%comunicar%'
    OR lower(coalesce(`resumen`, '')) LIKE '%contactar%'
    THEN 'contacto_general'
  WHEN lower(coalesce(`resumen`, '')) LIKE '%reclamo%'
    OR lower(coalesce(`resumen`, '')) LIKE '%reclamar%'
    OR lower(coalesce(`resumen`, '')) LIKE '%queja%'
    OR lower(coalesce(`resumen`, '')) LIKE '%disconform%'
    THEN 'reclamos'
  ELSE 'sin_clasificar'
END;
